version:
  name: velociraptor
  version: 0.5.0
  commit: 6fc96b5f
  build_time: "2020-09-22T18:21:45+10:00"
Client:
  server_urls:
  - https://localhost:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDKjCCAhKgAwIBAgIQKrj7Gg/NxTsXagiDp006MDANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjAxMDA3MDE0OTEyWhcNMzAx
    MDA1MDE0OTEyWjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCfbFpnje/0++Yqd7mZScHYpx6Kk2v4YQ9V
    KFHJ6MYgqjTlV17vqEUPJZn0yTmJqc4LXNWoMomPyDqJTtQ4rQdI+dRss9LC+6A6
    pl50mKxl6sC4Q64HetxA4K2MYbnNK9+WCZIxPJsfJt47eIKshBLYUrK5UQ8UXvWf
    vKOdv34j8yWXp5nLaKYIkK+1jA0F3CvF6r+J/WQ1yqOTtAPwtoJ9VzEBvyvdX4Id
    H5d7B0vR6g9x4gftwFDJp4to/5cRviQGGJyU5eaM6rm709mX1KlNljVrYbUctVeN
    R3suVUGIOTuXogUR2meL9X3Jt99WPeCjGd1dGc8v0L5Y9X2gSaKpAgMBAAGjbDBq
    MA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
    DwYDVR0TAQH/BAUwAwEB/zAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVs
    b2NpZGV4LmNvbTANBgkqhkiG9w0BAQsFAAOCAQEAb8I12zcu0VwtZHUxBoHm9XyQ
    mNXGZH76Pc/hM+7dkf9EK937nO9WJ7xfN0kpA9553A3OXQfaECqJwxSb5gPBVaQT
    6HOKb5ePt7nCfp1CmIGckqSXDyI75PcDec8/UYg5ptLZS/hnxCw89Az0uCWTu2ww
    dzt911lqPMx2iWkmcQlzKFkpeGSRUvu1rWumFEV5By6KOSvhplRZEPik43fqgn1U
    doC0HoxDrose+tU/RZDp9fv4oefZmUmImnMzFge2kVmg758t+I4od45J8U7YdX/q
    G6H8ChH7Gx4p0sLzmJFt+z9xIRNeIUGhlwGIwqACxRCMLDcksXtvafhzu6AZSQ==
    -----END CERTIFICATE-----
  nonce: nI4VWgLNNzI=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.5.0
    commit: 6fc96b5f
    build_time: "2020-09-22T18:21:45+10:00"
  use_self_signed_ssl: true
  pinned_server_name: VelociraptorServer
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
API:
  hostname: localhost
  bind_address: 127.0.0.1
  bind_port: 8001
  bind_scheme: tcp
  pinned_gw_name: GRPC_GW
GUI:
  bind_address: 127.0.0.1
  bind_port: 8889
  gw_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDDDCCAfSgAwIBAgIQfKgg5+RmWSLkFQKIikHmrzANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjAxMDA3MDE0OTEyWhcNMjEx
    MDA3MDE0OTEyWjApMRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxEDAOBgNVBAMMB0dS
    UENfR1cwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCrpV/WEuZr+mI+
    fHejQO0CDbFTJadB1kSL6v1e7R3LBVNsg+qIGAl/v1C87cP0yXHeKX1w/eIa3YWm
    PwQtXIIZI4C9wBI0MBsaSqbY/E6YpRsAo8pRTmTxZkfsaFVYvi8chbONRioSPHCc
    /VoLwt8RXVaOdns9rYTAZCfWu+qjfn5RBmRWFpr3eLvs2CS7NfR65pc7tlEk8ZgL
    WhGd40vwqJBfCC8v9kChVt1/7O7uZeIPjy53mEP6k1aU02eKEv+pDMt5BIeOLzXO
    7QxJE7mXz+3ongN5pvfA0mSFp9u/1jnRoyOG4J1MZcScv1C7ozpVCZzCimTHcfcG
    HXnAJTftAgMBAAGjPzA9MA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEF
    BQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADANBgkqhkiG9w0BAQsFAAOCAQEA
    LeWT5Mp3vYKBc7dTTv8Ok30EvkFcfZngHBN/K2xojtM8JokYc94I3TGesNTO/i74
    7G3lfKEYDDjO1uug4iYMPTcP97UR2emX+qIJt+OtU5ljpMDCpKi+gTkVgZQUsHWB
    6CMDGrgEYbJXprelJ8/8n86Ub3lVrwzbwHO7QRScRhhU54o4qum44cdwD+jml4CX
    9PhJXVRFjsqpCvZrtYRPQERpSR8oB98n92681GAr62+ckiE5pHCuuaYOUnm0CtxL
    PKnVfJyqoBNHtud6HESttq8lrjTJqIldqWgK43TU/J5fzzCjNgC9OtDAVBRsalBS
    do8wcCktIvz2vb9rJBbeAw==
    -----END CERTIFICATE-----
  gw_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAq6Vf1hLma/piPnx3o0DtAg2xUyWnQdZEi+r9Xu0dywVTbIPq
    iBgJf79QvO3D9Mlx3il9cP3iGt2Fpj8ELVyCGSOAvcASNDAbGkqm2PxOmKUbAKPK
    UU5k8WZH7GhVWL4vHIWzjUYqEjxwnP1aC8LfEV1WjnZ7Pa2EwGQn1rvqo35+UQZk
    Vhaa93i77NgkuzX0euaXO7ZRJPGYC1oRneNL8KiQXwgvL/ZAoVbdf+zu7mXiD48u
    d5hD+pNWlNNnihL/qQzLeQSHji81zu0MSRO5l8/t6J4Deab3wNJkhafbv9Y50aMj
    huCdTGXEnL9Qu6M6VQmcwopkx3H3Bh15wCU37QIDAQABAoIBABlqW05vbf7/DB0E
    gRKDQpTTQjZ1lNaCy5OMMAgmRAsTts6Smd+c74si4OmYqzNLwLiMnC5m6VvhATEk
    k5HD6N+gCigOkKN5nAnAlAP9GAYyLFVj60kuunOkGXI/4KNLRd6LTZLVmNUqbeJR
    AUxMhosjrvVZRdZUIxv5uIxrNssOaZ4yQiVv0nBT/WCJD0LXmDl+NEZaRCi9Z/B5
    BsWU/Y3dka2TaLXkFVK/uccuvxB3p90/B3KH1OfqzAQMx9H5tqIpAxom5OhSaieP
    JqBURlGU86cSaaV4DxQKJmQo769+qmDfDJtHd74lvMS+b33xtRGeoI2mS7tT2dpO
    lT06XmECgYEAxA0Jq3LY4yShf68n6UgIT6skM2N/LnJqXPe+uAEzG3XK9hBqcc+g
    whk1ThlIjDcR5Gj1qjfDgnuKuErVPbsmSzVRacOdQKq/TqJ9ZkQZ7i2Muh9okLg5
    eksMjlV4TnldFFWvd+klAcy+DN5RzN1tzrAfD1giwIwRI7585bon/vcCgYEA4CHo
    B9PIYRROiZNqK4S5srZDnBLsx94sdm/PE5THvnBxIvuKXl7w83uLzvRzrhSlBiyk
    yhCTWJzMk8RhCtE0p+Xq8IEC1+X80SwwzevI3gs0gIA80OK6ZvsfQafd/HxVbhi4
    2tRJWe0LQUfyJuRMIlK4sCAljCE4KumzKY4f8zsCgYB6oC0MMCm46ZCabNRp9cQ9
    EK7z9af3RVmCDPQd46Iz6tmoT1xFE7lZrqrIzsex7EAkvgHrFjYTx3JdE3GNyyGI
    qTDjFpeleydt5/THopEViSgcwsiEvLY25/pSjONTMlYmAfJe7lVXatj085n2qgmk
    3kSPNHGIPhP6Z4t3pZiewQKBgGBGUDvkfcMtjNrNpqJQ3c9lOT92ZZ0o0yKAvotj
    sjUcaYykTfhhgdCkthZMrNAO8B/p11MwsYozuDCU/zY9TQf92+A5GnaQxPs4pzIc
    4Oh4GbJE41q6uWT446E5MUJ+SdgD6Iue+m8VQmtlMx//mrB3pfuJo3dA4baVMi9c
    bF73AoGBAK9/VFH4ipXcAdXEtgW2RJPV+sfIG7PtnldbjbXTT3QickKXZps5AGpx
    tzRDrTeBJVwH8u6M9awAJ+mdXDyPKhP0wFSJ9/xkdZHR092v8gpFFwuk0DLF63ie
    OhgxN7YSpETT2WCPwiOEF+9zrZFvFCJJXvvY4pWMqwd87m08fSa8
    -----END RSA PRIVATE KEY-----
  internal_cidr:
  - 127.0.0.1/12
  - 192.168.0.0/16
  initial_users:
  - name: admin
    password_hash: 52c9234849bf12294d0bac9e8ed38fdd47783980c2f3e2faa13240e41dd1c2f3
    password_salt: 7cc4647229520efa42293960b7bfee519ab4fbe6b61c324550e85761f04cb440
  authenticator:
    type: Basic
CA:
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEAn2xaZ43v9PvmKne5mUnB2KceipNr+GEPVShRyejGIKo05Vde
    76hFDyWZ9Mk5ianOC1zVqDKJj8g6iU7UOK0HSPnUbLPSwvugOqZedJisZerAuEOu
    B3rcQOCtjGG5zSvflgmSMTybHybeO3iCrIQS2FKyuVEPFF71n7yjnb9+I/Mll6eZ
    y2imCJCvtYwNBdwrxeq/if1kNcqjk7QD8LaCfVcxAb8r3V+CHR+XewdL0eoPceIH
    7cBQyaeLaP+XEb4kBhiclOXmjOq5u9PZl9SpTZY1a2G1HLVXjUd7LlVBiDk7l6IF
    Edpni/V9ybffVj3goxndXRnPL9C+WPV9oEmiqQIDAQABAoIBADcI0Kyu8wc/blV6
    vzeLnr+L8Z8lBUDZQNHE+XcaREtCdsA1STCyhiSUdnFqhdJgLCEAC0HlMFfSZ2K/
    M8Pc94bZt9tOuJNXChk1FaZqjhkg0SbLNmieoSpEZaTwl5OccbL52t3kbihy4oTl
    NTcY4OiMo+YVdX8yyNg75r+uO31tByksY8uX3NMH1wds03VBUMwNEWWMJxTNN/yz
    V38JzFngVu4sq0CKE07Uak8M8Me9FY3bNJrxA5Ppv6Aw93RNzDUHAwRa6IMakKvJ
    mdM+pE2A7Sadcb34C1GElFaUrzPdkmvBXSIZgjogIkVzZEh1uaFZzCoBNBAs2mQn
    /ikIIYECgYEAxZEkkwGAMqWJZR0ZhPOkqOBu33S4fVw2zUMqT3Sg7ooYROUMgTDr
    LskYp3oxZR2nx5KsXWv2I71QBSOZXao6J8fum88WoZmrqn0AIv1Fhyf64GBSq4mN
    IEhAQa3V6om1IUf+gFU8yjSl6OBFTql4XOgOezMYwYY+5BZVfxa42ksCgYEAzpMl
    GPvtEAzMKAYeOL/JXc/ITk+YClMC2ujZ3HgWLFmTGZJWaELYCedPy8E0xYUHpvqK
    AYVY24V+DCIWqIHjknrHPdZ9Smdxh2N2l3/ZdUp7KpfLDOK09xInvytNqucyj4YX
    Sa0mzI2ZIJ3jEOci6Te/MOBZEFzLqv7i9JF13lsCgYBHtT2sKdBJEbJDxAMeMXyj
    WwqDCo9n2M9/QxCZVECRNAhJAUW/omzKR20uZHiHNfNOyZrMMcJeCHmB1AD3cTC4
    faXKYajaMLeRItuo13qj6svxIqT+4+cYP4ErFZheD2txz/q8w7NTxTYuxzAAtBwe
    xI91Af/LRhmPmdegUDP57wKBgAfokDoFowzDQKmjmlKX3RCvXL7Kw0pZ5TkWQwjy
    u/6Uq1IGTTKOpJC0f1SQoAGT1zgoTVJDlaRJ1wqF35Ix7tFzy97tMDzB+xGw2CBy
    r5OS92YpC4gBweXXlxf1g3KwiTn/azLR4zNflGYwRTonbym4jaREYoSC2PVB7tRo
    ITgTAoGACn9Vvl3wA4tvQtP2q4xp/yo8LFLE0E3LzNYDfRnNQJBCJItmm4EVj5qQ
    XnxNXwrOSQOSSbrNnKF0fKpymQNSIOP8+oi5PyAQNgZVsh3U6fiVPnyuQp3MWjRk
    gjpP6FV6D0GLL5tqF4m4X4hBjpPqAw4jBReWG8jpkUsAwrcfb/g=
    -----END RSA PRIVATE KEY-----
Frontend:
  hostname: localhost
  bind_address: 0.0.0.0
  bind_port: 8000
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDGDCCAgCgAwIBAgIRAIy5sv41Y8x+aBxuaoY/rkswDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTIwMTAwNzAxNDkxMloXDTIx
    MTAwNzAxNDkxMlowNDEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMRswGQYDVQQDExJW
    ZWxvY2lyYXB0b3JTZXJ2ZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
    AQDc+KeVFGxu8gdpsMvKSAohBmmNCdGlWWvlvBVjgEHS5PqAQMRfMbzr63UsNtuZ
    pwJO9aO76rZt9LhjJIPY6cfDKXatk4i7UxVciDqtkh1081ZzvTCky7P4l2rLrvCZ
    8DETFifUOPRdHCMvfWTfwPOnHGSQwzKC11YIhYU00MawxtApwEOBqs4RxSM+4nVd
    ZO+oNKti9/eVesu7GDF7BWkYXPgDLzHRKlMD0l/b3OhwJVf5jX6SQVc3HSwnTGaZ
    PVyplrCBh9dbbGaw7ts9ezPBqAKWyWi6OF4HjZi9sZSGeBawPiM8ZKRRwvAZaeXT
    ppZrrxrlAqw9lb2CckHQPRtdAgMBAAGjPzA9MA4GA1UdDwEB/wQEAwIFoDAdBgNV
    HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADANBgkqhkiG
    9w0BAQsFAAOCAQEAlQe1E1OWcIYzCq7uOHK6/wSzhKUrA6u1q3eWiyGw3h9mSFSt
    OvV4lWXaJ1lHJWrVn+LKjD/AEMeLEpohSAWyEKmUG1Ngrr0wlx6h+y+rF9qjqWxg
    ucfZm7y22qaaR3PVSU8C+dCYuxUZq7lri/IUlCmsrQ6+QvKO/MWb7HGPY5hvknUB
    QBGiRGZ9lktQUZWH4tuFzE6I8evn1NpuvAl0RMAkmvrY/xDZgJt7LCEoQz9W8um0
    9vK/KrpnCDEDBOCbPLtb4VJh2DCoPfnPhCT5HDtgNyhVMRRHvhzRgS5wbZc82SbH
    JUWE5YwI93UwJXVLV7k3Qh+qN3Ef33ElUd6EDQ==
    -----END CERTIFICATE-----
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEA3PinlRRsbvIHabDLykgKIQZpjQnRpVlr5bwVY4BB0uT6gEDE
    XzG86+t1LDbbmacCTvWju+q2bfS4YySD2OnHwyl2rZOIu1MVXIg6rZIddPNWc70w
    pMuz+Jdqy67wmfAxExYn1Dj0XRwjL31k38DzpxxkkMMygtdWCIWFNNDGsMbQKcBD
    garOEcUjPuJ1XWTvqDSrYvf3lXrLuxgxewVpGFz4Ay8x0SpTA9Jf29zocCVX+Y1+
    kkFXNx0sJ0xmmT1cqZawgYfXW2xmsO7bPXszwagClsloujheB42YvbGUhngWsD4j
    PGSkUcLwGWnl06aWa68a5QKsPZW9gnJB0D0bXQIDAQABAoIBAEBnJIi5zCTF2809
    HxhUyMb5VHgr3XOAzYbGu8ElV4n8/Nm2hsVr/LESDjOVxYlR+MVEqLUTYppHkhor
    QVZORM+n3RQYBOj7/STb+6YtCPLWHWNcR7owOMMCdrjowu1K6TKz6WXcN7SPh93G
    gUkJtroE93aNvcIOut9+8uUC2HYa4Se2zY+u50K+DBcxvGcUgZ1z/tVLimE258Ch
    a+ei9zUpjXni0SvtG02TGkUIAiIVieDTerYwKSI5y9rbChGISrlp120bAF9xgjK6
    ZCQxzo1frzSI59at/MhS7Cco+Rz3IWJqcZWe5S+FI+x5nDi67TxkUNar1mOYr2yH
    lD4owCECgYEA4XJsK4WTqbrHc0ND68/tXJtnitSmDhQq4Z0IuepLgPXVjnTE2DlI
    dTltWZNKd50wkUddzdIti+x//535OVjuwFoSCz7dWIhrhav6NR6lPJBJU3ZLyw0N
    0oy8c1SWEFIhkYlqUay2qs+VoAQqA7iGBdG/AcaDSG28lglyVlLGGMkCgYEA+ur0
    i0QYcVdxSSSKDOYji5Jtx0PWbSkbXS7/r2mbMMLP23wM1yMrjMbx3AYXmut8rWoF
    09DHSeYtUO3ANOV148NSMADQZ4038OXoX7/yfUgmnSoqb3T8SW2o5Gha8k5qdVDp
    00197fM1dJ+KyySdOK1S5ddxNZTBgxNQuesAy/UCgYEAwfwZtU0npKjxi206mUJ9
    Y+zYKC4XgA+8YgskAgzm0N0213AEHGUVwsAaJjRFpCyeKLN2tG4AAOELth/w3XZ3
    YQ1fb0u1W8NueUNkdKac2ULxxR4J03q1BRFR6g7DXOG+vqK11/c76jfZ8CkFGdSB
    hapXpyhvuDesSJFyT3LDv3kCgYEAhFNYeAGHam6U/d/ZNghAgqDMaCPsd1EQb0oT
    6WwmPcbfW37GPsb7dpiMgF5uIHNEIyggvp4CG4TaLS3VCZBhZaZiN5KWVaXx9Icq
    zyQpO8zLIGNWUcU+L3M3eI1YOSUFm6z6Q0dAvDZg4Ioq5gr/Jx6w8yl1OK6khv2u
    uv2mQ+kCgYEAkeSulMPqakaUwb7/0wBMxDhmMsZispDSzPytxqXHAvmCAXxL+z5L
    OdSn0EJeWtIIbCTcqstziHOPyugAif+hkB4t5tv7V0JZ0JQC1KjGXPV+DBNMLJJ5
    Cs3lgLd5KglwL0JIQ4DrC9DPT8LsQCarndFIGIc4+RumJFivG/7VK48=
    -----END RSA PRIVATE KEY-----
  max_upload_size: 10485760
  dyn_dns: {}
  default_client_monitoring_artifacts:
  - Generic.Client.Stats
  expected_clients: 10000
  GRPC_pool_max_size: 100
  GRPC_pool_max_wait: 60
Datastore:
  implementation: FileBaseDataStore
  location: /opt/velociraptor
  filestore_directory: /opt/velociraptor
Writeback: {}
Mail: {}
Logging:
  output_directory: /opt/velociraptor/logs
  separate_logs_per_component: true
Monitoring:
  bind_address: 127.0.0.1
  bind_port: 8003
api_config: {}
server_type: linux
obfuscation_nonce: D1FAmv2fEf0=
